export const programmingAndDesignTools = [
    "JavaScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "TypeScript",
    "Ruby",
    "Swift",
    "Kotlin",
    "Go",
    "Wordpress",
    "Next.js",
    "Remix",
    "Nest.js",
    "Rust",
    "PHP",
    "HTML",
    "CSS",
    "SQL",
    "Scala",
    "Dart",
    "R",
    "React",
    "Angular",
    "Vue.js",
    "jQuery",
    "Bootstrap",
    "Tailwind CSS",
    "Sass",
    "Less",
    "Ember.js",    
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Laravel",
    "Symfony",
    "FastAPI",    
    "React Native",
    "Flutter",    
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "SQLite",
    "Redis",    
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Sketch",
    "Figma",
    "Adobe XD",
    "InVision",
    "Canva",    
    "Material-UI",
    "Ant Design",
    "Chakra UI",
    "Semantic UI",
    
    // Other Tools
    "Postman",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Heroku",
    "Netlify",
    "Vercel",
    "AWS",
    "Azure",
    "Slack",
    "Microsoft Teams",
    "Trello",
    "Jira",
    "Notion",
];